language: node_js
node_js:
    - "lts/*"
before_install:
    - yarn global add grunt-cli
    - yarn global add bower
    - bower install
notifications:
    email:
        on_success: change
        on_failure: change
sudo: false
cache:
    yarn: true
